CREATE TABLE #staging_candidatos_2016(
    data_geracao DATE,
    hh_gerecao TIME,
    ano_eleicao INT,
    cd_tipo_eleicao INT,
    nm_tipo_eleicao VARCHAR(50),
    nr_turno INT,
    cd_eleicao INT,
    ds_eleicao VARCHAR(100),
    dt_eleicao DATE,
    tp_abrangencia VARCHAR(100),
    sg_uf VARCHAR(10),
    sg_ue INT,
    nm_ue VARCHAR(100),
    cd_cargo INT,
    ds_cargo VARCHAR(100),
    sq_candidato BIGINT,
    nr_candidato INT,
    nm_candidato VARCHAR(100),
    nm_urna_candidato VARCHAR(100),
    nm_social_candidato VARCHAR(100),
    nr_cpf_candidato VARCHAR(50),
    nm_email VARCHAR(100),
    cd_situacao_candidatura INT,
    ds_situacao_candidatura VARCHAR(50),
    cd_detalhe_situacao_cand INT,
    ds_detalhe_situacao_cand VARCHAR(100),
    tp_agremiacao VARCHAR(100),
    nr_partido INT,
    sg_partido VARCHAR(50),
    nm_partido VARCHAR(100),
    nr_federacao INT,
    nm_federacao VARCHAR(100),
    sg_federacao VARCHAR(50),
    ds_composicao_federacao VARCHAR(100),
    sq_coligacao INT,
    nm_coligacao VARCHAR(100),
    ds_composicao_coligacao VARCHAR(100),
    cd_nascionalidade INT,
    ds_nascionalidade VARCHAR(100),
    sg_uf_nascimento VARCHAR(10),
    cd_municipio_nascimento INT,
    nm_muninipio_nascimento VARCHAR(100),
    dt_nascimento DATE,
    nr_idade_data_posse INT,
    nr_titulo_eleitoral_candidato VARCHAR(100),
    cd_genero INT,
    ds_genero VARCHAR(50),
    cd_grau_instrucao INT,
    ds_grau_instrucao VARCHAR(50),
    cd_estado_civil INT,
    ds_estado_civil VARCHAR(50),
    cd_cor_raca INT,
    ds_cor_raca VARCHAR(50),
    cd_ocupacao INT,
    ds_ocupacao VARCHAR(50),
    vr_despesa_max_campanha FLOAT,
    cd_sit_tot_turno INT,
    ds_sit_tot_turno VARCHAR(50),
    st_reeleicao VARCHAR(10),
    st_declarar_bens VARCHAR(10),
    nr_protocolo_candidatura BIGINT,
    nr_processo BIGINT,
    cd_situacao_candidato_pleito INT,
    ds_situacao_candidato_pleito VARCHAR(50),
    cd_situacao_candidato_urna INT,
    ds_situacao_candidato_urna VARCHAR(50),
    st_candidato_inserido_urna VARCHAR(50),
    nm_tipo_destinacao_votos VARCHAR(100),
    cd_situacao_candidato_tot INT,
    ds_situacao_candidato_tot VARCHAR(100),
    st_prest_contas VARCHAR(10),
    st_substituido VARCHAR(10),
    sq_substituido INT,
    sq_ordem_suplencia INT,
    dt_aceite_candidatura DATETIME2
);

-- Usei um BULK INSERT ao inves de fazer no Excel
-- Eu fiz o INSERT manualmente quando os arquivos não estavam em .csv

BULK INSERT #staging_candidatos_2016
FROM '/caminho/para/arquivo.csv'
WITH (
FIRSTROW = 2,
FIELDTERMINATOR = ';',
ROWTERMINATOR = '\n',
CODEPAGE = '65001',
TABLOCK -- Bloqueia a tabela durante a operação
);
-- o comando acima só funciona se o arquivo estiver no mesmo ambiente de execucao, nesse caso na AWS
